SMS_CODE_REDIS_EXPIRES = 300  # 验证码保存时间
SEND_SMS_CODE_INTERVAL = 60  # 验证码有效时间
IMAGE_CODE_REDIS_EXPIRES = 300  # 图片验证码有效期
VERIFY_EMAIL_TOKEN_EXPIRES = 300  # token连接有效期
EMAIL_CODE_REDIS_EXPIRES = 300  # 邮件验证码有效期
SEND_EMAIL_CODE_INTERVAL = 60  # 邮箱验证码有效时间
